version: "3.8"
services:
  postgres:
    image: postgres:15.10-alpine
    container_name: tictactoe-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tiktaktoe_database
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
